// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Telenor.Api.TestExecutionManagement.Infrastructure.Data;

#nullable disable

namespace Telenor.Api.TestExecutionManagement.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Telenor.Api.TestExecutionManagement.Core.Entities.CycleFolder", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CycleId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CycleId");

                    b.ToTable("CycleFolders");
                });

            modelBuilder.Entity("Telenor.Api.TestExecutionManagement.Core.Entities.ExecutionHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExecutionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionId", "ChangedAt");

                    b.ToTable("ExecutionHistory");
                });

            modelBuilder.Entity("Telenor.Api.TestExecutionManagement.Core.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("JiraProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("JiraProjectId")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Telenor.Api.TestExecutionManagement.Core.Entities.TestCase", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("JiraIssueId")
                        .HasColumnType("int");

                    b.Property<string>("JiraIssueKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JiraIssueKey");

                    b.HasIndex("ProjectId");

                    b.ToTable("TestCases");
                });

            modelBuilder.Entity("Telenor.Api.TestExecutionManagement.Core.Entities.TestCycle", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("VersionId");

                    b.ToTable("TestCycles");
                });

            modelBuilder.Entity("Telenor.Api.TestExecutionManagement.Core.Entities.TestExecution", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("AssignedTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CycleId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FolderId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("TestCaseId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TestCaseId");

                    b.HasIndex("VersionId");

                    b.HasIndex("CycleId", "FolderId");

                    b.HasIndex("CycleId", "StatusId");

                    b.ToTable("TestExecutions");
                });

            modelBuilder.Entity("Telenor.Api.TestExecutionManagement.Core.Entities.Version", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsReleased")
                        .HasColumnType("bit");

                    b.Property<int?>("JiraVersionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Versions");
                });

            modelBuilder.Entity("Telenor.Api.TestExecutionManagement.Core.Entities.CycleFolder", b =>
                {
                    b.HasOne("Telenor.Api.TestExecutionManagement.Core.Entities.TestCycle", "Cycle")
                        .WithMany("Folders")
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cycle");
                });

            modelBuilder.Entity("Telenor.Api.TestExecutionManagement.Core.Entities.ExecutionHistory", b =>
                {
                    b.HasOne("Telenor.Api.TestExecutionManagement.Core.Entities.TestExecution", "Execution")
                        .WithMany("History")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Execution");
                });

            modelBuilder.Entity("Telenor.Api.TestExecutionManagement.Core.Entities.TestCase", b =>
                {
                    b.HasOne("Telenor.Api.TestExecutionManagement.Core.Entities.Project", "Project")
                        .WithMany("TestCases")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Telenor.Api.TestExecutionManagement.Core.Entities.TestCycle", b =>
                {
                    b.HasOne("Telenor.Api.TestExecutionManagement.Core.Entities.Project", "Project")
                        .WithMany("TestCycles")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Telenor.Api.TestExecutionManagement.Core.Entities.Version", "Version")
                        .WithMany("TestCycles")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Telenor.Api.TestExecutionManagement.Core.Entities.TestExecution", b =>
                {
                    b.HasOne("Telenor.Api.TestExecutionManagement.Core.Entities.TestCycle", "Cycle")
                        .WithMany("Executions")
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Telenor.Api.TestExecutionManagement.Core.Entities.CycleFolder", "Folder")
                        .WithMany("Executions")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Telenor.Api.TestExecutionManagement.Core.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Telenor.Api.TestExecutionManagement.Core.Entities.TestCase", "TestCase")
                        .WithMany("Executions")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Telenor.Api.TestExecutionManagement.Core.Entities.Version", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cycle");

                    b.Navigation("Folder");

                    b.Navigation("Project");

                    b.Navigation("TestCase");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Telenor.Api.TestExecutionManagement.Core.Entities.Version", b =>
                {
                    b.HasOne("Telenor.Api.TestExecutionManagement.Core.Entities.Project", "Project")
                        .WithMany("Versions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Telenor.Api.TestExecutionManagement.Core.Entities.CycleFolder", b =>
                {
                    b.Navigation("Executions");
                });

            modelBuilder.Entity("Telenor.Api.TestExecutionManagement.Core.Entities.Project", b =>
                {
                    b.Navigation("TestCases");

                    b.Navigation("TestCycles");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Telenor.Api.TestExecutionManagement.Core.Entities.TestCase", b =>
                {
                    b.Navigation("Executions");
                });

            modelBuilder.Entity("Telenor.Api.TestExecutionManagement.Core.Entities.TestCycle", b =>
                {
                    b.Navigation("Executions");

                    b.Navigation("Folders");
                });

            modelBuilder.Entity("Telenor.Api.TestExecutionManagement.Core.Entities.TestExecution", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("Telenor.Api.TestExecutionManagement.Core.Entities.Version", b =>
                {
                    b.Navigation("TestCycles");
                });
#pragma warning restore 612, 618
        }
    }
}
